from typing import Dict, List

MUSCLE_GROUPS: Dict[str, str] = {
    "quadriceps": "Квадрицепсы",
    "hamstrings": "Бицепсы бедра",
    "glutes": "Ягодицы",
    "calves": "Икры",
    "chest": "Грудь",
    "back": "Спина",
    "shoulders": "Плечи",
    "biceps": "Бицепсы",
    "triceps": "Трицепсы",
    "abs": "Пресс",
    "forearms": "Предплечья",
    "full_body": "Полное тело",
}

EQUIPMENT: Dict[str, str] = {
    "barbell": "Штанга",
    "dumbbell": "Гантели",
    "machine": "Тренажёр",
    "cable": "Кабель",
    "bodyweight": "Собственный вес",
    "kettlebell": "Гиря",
    "resistance_band": "Резинка",
    "smith_machine": "Смит",
    "ez_bar": "EZ-штанга",
    "sled": "Сани",
    "sandbag": "Мешок",
    "medicine_ball": "Медбол",
}

EXERCISE_SEED: List[dict] = [
    {"name": "Приседания со штангой на спине", "muscle_group": "quadriceps", "equipment": "barbell", "is_compound": True},
    {"name": "Приседания со штангой на груди", "muscle_group": "quadriceps", "equipment": "barbell", "is_compound": True},
    {"name": "Приседания с гантелью (гоблет)", "muscle_group": "quadriceps", "equipment": "dumbbell", "is_compound": True},
    {"name": "Гакк-приседания", "muscle_group": "quadriceps", "equipment": "machine", "is_compound": True},
    {"name": "Гакк-приседания (Смит)", "muscle_group": "quadriceps", "equipment": "smith_machine", "is_compound": True},
    {"name": "Жим ногами", "muscle_group": "quadriceps", "equipment": "machine", "is_compound": True},
    {"name": "Приседания с сэйфти-грифом", "muscle_group": "quadriceps", "equipment": "barbell", "is_compound": True},
    {"name": "Приседания Зерхера", "muscle_group": "quadriceps", "equipment": "barbell", "is_compound": True},
    {"name": "Приседания с поясом", "muscle_group": "quadriceps", "equipment": "machine", "is_compound": True},
    {"name": "Приседания с паузой", "muscle_group": "quadriceps", "equipment": "barbell", "is_compound": True},
    {"name": "Темповые приседания", "muscle_group": "quadriceps", "equipment": "barbell", "is_compound": True},
    {"name": "Приседания в Смите", "muscle_group": "quadriceps", "equipment": "smith_machine", "is_compound": True},
    {"name": "Болгарские сплит-приседания", "muscle_group": "quadriceps", "equipment": "dumbbell", "is_compound": True},
    {"name": "Болгарские сплит-приседания (с задней ногой на возвышении)", "muscle_group": "quadriceps", "equipment": "bodyweight", "is_compound": True},
    {"name": "Обратные выпады", "muscle_group": "quadriceps", "equipment": "dumbbell", "is_compound": True},
    {"name": "Выпады с ходьбой", "muscle_group": "quadriceps", "equipment": "dumbbell", "is_compound": True},
    {"name": "Реверанс-выпады", "muscle_group": "quadriceps", "equipment": "dumbbell", "is_compound": True},
    {"name": "Разгибание ног", "muscle_group": "quadriceps", "equipment": "machine", "is_compound": False},
    {"name": "Разгибание ног сидя", "muscle_group": "quadriceps", "equipment": "machine", "is_compound": False},
    {"name": "Разгибание одной ноги", "muscle_group": "quadriceps", "equipment": "machine", "is_compound": False},
    {"name": "Приседания 'Сисси'", "muscle_group": "quadriceps", "equipment": "bodyweight", "is_compound": True},
    {"name": "Румынская тяга", "muscle_group": "hamstrings", "equipment": "barbell", "is_compound": True},
    {"name": "Становая тяга на прямых ногах", "muscle_group": "hamstrings", "equipment": "barbell", "is_compound": True},
    {"name": "Становая тяга на прямых ногах (с гантелями)", "muscle_group": "hamstrings", "equipment": "dumbbell", "is_compound": True},
    {"name": "Сгибание ног лежа", "muscle_group": "hamstrings", "equipment": "machine", "is_compound": False},
    {"name": "Сгибание ног сидя", "muscle_group": "hamstrings", "equipment": "machine", "is_compound": False},
    {"name": "Сгибание ног стоя", "muscle_group": "hamstrings", "equipment": "machine", "is_compound": False},
    {"name": "Наклоны 'Доброе утро'", "muscle_group": "hamstrings", "equipment": "barbell", "is_compound": True},
    {"name": "Наклоны 'Доброе утро' (с гантелями)", "muscle_group": "hamstrings", "equipment": "dumbbell", "is_compound": True},
    {"name": "Румынская тяга на одной ноге", "muscle_group": "hamstrings", "equipment": "dumbbell", "is_compound": True},
    {"name": "Румынская тяга на одной ноге (с гирей)", "muscle_group": "hamstrings", "equipment": "kettlebell", "is_compound": True},
    {"name": "Глют-Хэм подъемы", "muscle_group": "hamstrings", "equipment": "bodyweight", "is_compound": True},
    {"name": "Протяжка на кабеле", "muscle_group": "hamstrings", "equipment": "cable", "is_compound": True},
    {"name": "Махи гирей", "muscle_group": "full_body", "equipment": "kettlebell", "is_compound": True},
    {"name": "Ягодичный мост", "muscle_group": "glutes", "equipment": "barbell", "is_compound": True},
    {"name": "Ягодичный мост (Смит)", "muscle_group": "glutes", "equipment": "smith_machine", "is_compound": True},
    {"name": "Ягодичный мост (с гантелями)", "muscle_group": "glutes", "equipment": "dumbbell", "is_compound": True},
    {"name": "Ягодичный мост (лежа)", "muscle_group": "glutes", "equipment": "bodyweight", "is_compound": True},
    {"name": "Ягодичный мост на одной ноге", "muscle_group": "glutes", "equipment": "bodyweight", "is_compound": True},
    {"name": "Тяга бедра на кабеле", "muscle_group": "glutes", "equipment": "cable", "is_compound": False},
    {"name": "Отведение ноги назад на кабеле", "muscle_group": "glutes", "equipment": "cable", "is_compound": False},
    {"name": "Тренажер для отведения бедра", "muscle_group": "glutes", "equipment": "machine", "is_compound": False},
    {"name": "Ракушка", "muscle_group": "glutes", "equipment": "resistance_band", "is_compound": False},
    {"name": "Пожарный гидрант", "muscle_group": "glutes", "equipment": "bodyweight", "is_compound": False},
    {"name": "Обратная гиперэкстензия", "muscle_group": "glutes", "equipment": "machine", "is_compound": False},
    {"name": "Удар осла", "muscle_group": "glutes", "equipment": "bodyweight", "is_compound": False},
    {"name": "Боковая ходьба с резинкой", "muscle_group": "glutes", "equipment": "resistance_band", "is_compound": False},
    {"name": "Лягушачий мостик", "muscle_group": "glutes", "equipment": "bodyweight", "is_compound": False},
    {"name": "Сумо-приседания", "muscle_group": "glutes", "equipment": "dumbbell", "is_compound": True},
    {"name": "Подъемы на носки стоя", "muscle_group": "calves", "equipment": "machine", "is_compound": True},
    {"name": "Подъемы на носки сидя", "muscle_group": "calves", "equipment": "machine", "is_compound": False},
    {"name": "Подъемы на носки осла", "muscle_group": "calves", "equipment": "machine", "is_compound": True},
    {"name": "Подъемы на носки (собственный вес)", "muscle_group": "calves", "equipment": "bodyweight", "is_compound": True},
    {"name": "Подъемы на носки (с гантелями)", "muscle_group": "calves", "equipment": "dumbbell", "is_compound": True},
    {"name": "Подъемы на носки (Смит)", "muscle_group": "calves", "equipment": "smith_machine", "is_compound": True},
    {"name": "Подъемы на носки в жиме ногами", "muscle_group": "calves", "equipment": "machine", "is_compound": True},
    {"name": "Подъемы на носки на одной ноге", "muscle_group": "calves", "equipment": "bodyweight", "is_compound": True},
    {"name": "Подъемы на носки на кабеле", "muscle_group": "calves", "equipment": "cable", "is_compound": False},
    {"name": "Подъемы на носки сидя (с гантелями)", "muscle_group": "calves", "equipment": "dumbbell", "is_compound": False},
    {"name": "Подъемы на носки с резинкой", "muscle_group": "calves", "equipment": "resistance_band", "is_compound": False},
    {"name": "Жим лежа", "muscle_group": "chest", "equipment": "barbell", "is_compound": True},
    {"name": "Жим лежа на наклонной скамье", "muscle_group": "chest", "equipment": "barbell", "is_compound": True},
    {"name": "Жим лежа на скамье под отрицательным углом", "muscle_group": "chest", "equipment": "barbell", "is_compound": True},
    {"name": "Жим гантелей лежа", "muscle_group": "chest", "equipment": "dumbbell", "is_compound": True},
    {"name": "Жим гантелей на наклонной скамье", "muscle_group": "chest", "equipment": "dumbbell", "is_compound": True},
    {"name": "Жим гантелей на скамье под отрицательным углом", "muscle_group": "chest", "equipment": "dumbbell", "is_compound": True},
    {"name": "Отжимания", "muscle_group": "chest", "equipment": "bodyweight", "is_compound": True},
    {"name": "Отжимания от возвышения", "muscle_group": "chest", "equipment": "bodyweight", "is_compound": True},
    {"name": "Отжимания с ногами на возвышении", "muscle_group": "chest", "equipment": "bodyweight", "is_compound": True},
    {"name": "Широкие отжимания", "muscle_group": "chest", "equipment": "bodyweight", "is_compound": True},
    {"name": "Алмазные отжимания", "muscle_group": "chest", "equipment": "bodyweight", "is_compound": True},
    {"name": "Разведение гантелей лежа", "muscle_group": "chest", "equipment": "dumbbell", "is_compound": False},
    {"name": "Разведение гантелей на наклонной скамье", "muscle_group": "chest", "equipment": "dumbbell", "is_compound": False},
    {"name": "Разведение гантелей на скамье под отрицательным углом", "muscle_group": "chest", "equipment": "dumbbell", "is_compound": False},
    {"name": "Кроссовер на кабеле", "muscle_group": "chest", "equipment": "cable", "is_compound": False},
    {"name": "Кроссовер на кабеле на наклонной скамье", "muscle_group": "chest", "equipment": "cable", "is_compound": False},
    {"name": "Пек-дек", "muscle_group": "chest", "equipment": "machine", "is_compound": False},
    {"name": "Жим лежа в Смите", "muscle_group": "chest", "equipment": "smith_machine", "is_compound": True},
    {"name": "Жим в Смите на наклонной скамье", "muscle_group": "chest", "equipment": "smith_machine", "is_compound": True},
    {"name": "Жим на грудь (тренажер)", "muscle_group": "chest", "equipment": "machine", "is_compound": True},
    {"name": "Жим на грудь на кабеле", "muscle_group": "chest", "equipment": "cable", "is_compound": True},
    {"name": "Отжимания на брусьях", "muscle_group": "chest", "equipment": "bodyweight", "is_compound": True},
    {"name": "Жим лежа узким хватом", "muscle_group": "triceps", "equipment": "barbell", "is_compound": True},
    {"name": "Становая тяга", "muscle_group": "back", "equipment": "barbell", "is_compound": True},
    {"name": "Классическая становая тяга", "muscle_group": "back", "equipment": "barbell", "is_compound": True},
    {"name": "Сумо становая тяга", "muscle_group": "back", "equipment": "barbell", "is_compound": True},
    {"name": "Становая тяга с трэп-грифом", "muscle_group": "back", "equipment": "barbell", "is_compound": True},
    {"name": "Подтягивания", "muscle_group": "back", "equipment": "bodyweight", "is_compound": True},
    {"name": "Подтягивания обратным хватом", "muscle_group": "back", "equipment": "bodyweight", "is_compound": True},
    {"name": "Подтягивания широким хватом", "muscle_group": "back", "equipment": "bodyweight", "is_compound": True},
    {"name": "Подтягивания нейтральным хватом", "muscle_group": "back", "equipment": "bodyweight", "is_compound": True},
    {"name": "Тяга верхнего блока", "muscle_group": "back", "equipment": "cable", "is_compound": False},
    {"name": "Тяга верхнего блока широким хватом", "muscle_group": "back", "equipment": "cable", "is_compound": False},
    {"name": "Тяга верхнего блока узким хватом", "muscle_group": "back", "equipment": "cable", "is_compound": False},
    {"name": "Тяга верхнего блока к задней части подошвы", "muscle_group": "back", "equipment": "cable", "is_compound": False},
    {"name": "Тяга штанги в наклоне", "muscle_group": "back", "equipment": "barbell", "is_compound": True},
    {"name": "Тяга Пендли", "muscle_group": "back", "equipment": "barbell", "is_compound": True},
    {"name": "Т-образная тяга", "muscle_group": "back", "equipment": "smith_machine", "is_compound": True},
    {"name": "Тяга горизонтального блока сидя", "muscle_group": "back", "equipment": "cable", "is_compound": False},
    {"name": "Тяга горизонтального блока узким хватом", "muscle_group": "back", "equipment": "cable", "is_compound": False},
    {"name": "Тяга с упором грудью (тренажер)", "muscle_group": "back", "equipment": "machine", "is_compound": False},
    {"name": "Тяга гантели одной рукой в наклоне", "muscle_group": "back", "equipment": "dumbbell", "is_compound": True},
    {"name": "Тяга гантелей в наклоне", "muscle_group": "back", "equipment": "dumbbell", "is_compound": True},
    {"name": "Тяга к лицу", "muscle_group": "back", "equipment": "cable", "is_compound": False},
    {"name": "Обратный пек-дек", "muscle_group": "back", "equipment": "machine", "is_compound": False},
    {"name": "Пуловер на кабеле", "muscle_group": "back", "equipment": "cable", "is_compound": True},
    {"name": "Прямые руки вниз на блоке", "muscle_group": "back", "equipment": "cable", "is_compound": False},
    {"name": "Тяга на тренажере", "muscle_group": "back", "equipment": "machine", "is_compound": True},
    {"name": "Обратная тяга", "muscle_group": "back", "equipment": "bodyweight", "is_compound": True},
    {"name": "Тяга штанги от пола (Landmine Row)", "muscle_group": "back", "equipment": "barbell", "is_compound": True},
    {"name": "Жим над головой", "muscle_group": "shoulders", "equipment": "barbell", "is_compound": True},
    {"name": "Жим со швунгом", "muscle_group": "shoulders", "equipment": "barbell", "is_compound": True},
    {"name": "Армейский жим", "muscle_group": "shoulders", "equipment": "barbell", "is_compound": True},
    {"name": "Жим гантелей сидя", "muscle_group": "shoulders", "equipment": "dumbbell", "is_compound": True},
    {"name": "Жим Арнольда", "muscle_group": "shoulders", "equipment": "dumbbell", "is_compound": True},
    {"name": "Жим гантелей стоя", "muscle_group": "shoulders", "equipment": "dumbbell", "is_compound": True},
    {"name": "Жим над головой в Смите", "muscle_group": "shoulders", "equipment": "smith_machine", "is_compound": True},
    {"name": "Махи гантелями в стороны", "muscle_group": "shoulders", "equipment": "dumbbell", "is_compound": False},
    {"name": "Махи гантелями в стороны", "muscle_group": "shoulders", "equipment": "dumbbell", "is_compound": False},
    {"name": "Махи на блоке в стороны", "muscle_group": "shoulders", "equipment": "cable", "is_compound": False},
    {"name": "Махи гантелями перед собой", "muscle_group": "shoulders", "equipment": "dumbbell", "is_compound": False},
    {"name": "Махи на блоке перед собой", "muscle_group": "shoulders", "equipment": "cable", "is_compound": False},
    {"name": "Разведение рук для задних дельт", "muscle_group": "shoulders", "equipment": "dumbbell", "is_compound": False},
    {"name": "Разведение рук для задних дельт (на кабеле)", "muscle_group": "shoulders", "equipment": "cable", "is_compound": False},
    {"name": "Разведение рук для задних дельт (на тренажере)", "muscle_group": "shoulders", "equipment": "machine", "is_compound": False},
    {"name": "Тяга к подбородку", "muscle_group": "shoulders", "equipment": "barbell", "is_compound": True},
    {"name": "Тяга к подбородку (на кабеле)", "muscle_group": "shoulders", "equipment": "cable", "is_compound": True},
    {"name": "Махи гантелями перед собой", "muscle_group": "shoulders", "equipment": "dumbbell", "is_compound": False},
    {"name": "Махи гантелями молотком", "muscle_group": "shoulders", "equipment": "dumbbell", "is_compound": False},
    {"name": "Шраги со штангой", "muscle_group": "back", "equipment": "barbell", "is_compound": True},
    {"name": "Шраги с гантелями", "muscle_group": "back", "equipment": "dumbbell", "is_compound": True},
    {"name": "Сгибания рук со штангой", "muscle_group": "biceps", "equipment": "barbell", "is_compound": False},
    {"name": "Сгибания рук с EZ-грифом", "muscle_group": "biceps", "equipment": "ez_bar", "is_compound": False},
    {"name": "Сгибания рук с гантелями", "muscle_group": "biceps", "equipment": "dumbbell", "is_compound": False},
    {"name": "Сгибания рук 'молот'", "muscle_group": "biceps", "equipment": "dumbbell", "is_compound": False},
    {"name": "Сгибания рук с гантелями на наклонной скамье", "muscle_group": "biceps", "equipment": "dumbbell", "is_compound": False},
    {"name": "Сгибания рук на кабеле", "muscle_group": "biceps", "equipment": "cable", "is_compound": False},
    {"name": "Сгибания рук 'молот' на кабеле", "muscle_group": "biceps", "equipment": "cable", "is_compound": False},
    {"name": "Сгибания рук на скамье Скотта", "muscle_group": "biceps", "equipment": "ez_bar", "is_compound": False},
    {"name": "Концентрированные сгибания", "muscle_group": "biceps", "equipment": "dumbbell", "is_compound": False},
    {"name": "Обратные сгибания рук", "muscle_group": "biceps", "equipment": "barbell", "is_compound": False},
    {"name": "Подтягивания (акцент на бицепс)", "muscle_group": "biceps", "equipment": "bodyweight", "is_compound": True},
    {"name": "Т-образные сгибания рук", "muscle_group": "biceps", "equipment": "barbell", "is_compound": False},
    {"name": "Разгибания рук на блоке", "muscle_group": "triceps", "equipment": "cable", "is_compound": False},
    {"name": "Разгибания рук с канатной рукояткой на блоке", "muscle_group": "triceps", "equipment": "cable", "is_compound": False},
    {"name": "Разгибания рук из-за головы с гантелью", "muscle_group": "triceps", "equipment": "dumbbell", "is_compound": False},
    {"name": "Французский жим", "muscle_group": "triceps", "equipment": "barbell", "is_compound": False},
    {"name": "Французский жим (EZ-гриф)", "muscle_group": "triceps", "equipment": "ez_bar", "is_compound": False},
    {"name": "Отжимания от скамьи", "muscle_group": "triceps", "equipment": "bodyweight", "is_compound": False},
    {"name": "Разгибания рук из-за головы на кабеле", "muscle_group": "triceps", "equipment": "cable", "is_compound": False},
    {"name": "Французский жим", "muscle_group": "triceps", "equipment": "ez_bar", "is_compound": False},
    {"name": "Разгибания рук назад", "muscle_group": "triceps", "equipment": "dumbbell", "is_compound": False},
    {"name": "Жим Джамшиди", "muscle_group": "triceps", "equipment": "barbell", "is_compound": True},
    {"name": "Отжимания узким хватом", "muscle_group": "triceps", "equipment": "bodyweight", "is_compound": True},
    {"name": "Планка", "muscle_group": "abs", "equipment": "bodyweight", "is_compound": False},
    {"name": "Боковая планка", "muscle_group": "abs", "equipment": "bodyweight", "is_compound": False},
    {"name": "Русские скручивания", "muscle_group": "abs", "equipment": "bodyweight", "is_compound": False},
    {"name": "Велосипед", "muscle_group": "abs", "equipment": "bodyweight", "is_compound": False},
    {"name": "Подъемы коленей в висе", "muscle_group": "abs", "equipment": "bodyweight", "is_compound": False},
    {"name": "Подъемы ног в висе", "muscle_group": "abs", "equipment": "bodyweight", "is_compound": False},
    {"name": "Скручивания с роликом для пресса", "muscle_group": "abs", "equipment": "bodyweight", "is_compound": False},
    {"name": "Скалолаз", "muscle_group": "abs", "equipment": "bodyweight", "is_compound": False},
    {"name": "Скручивания", "muscle_group": "abs", "equipment": "bodyweight", "is_compound": False},
    {"name": "Обратные скручивания", "muscle_group": "abs", "equipment": "bodyweight", "is_compound": False},
    {"name": "Подъемы ног", "muscle_group": "abs", "equipment": "bodyweight", "is_compound": False},
    {"name": "Скручивания на наклонной скамье", "muscle_group": "abs", "equipment": "bodyweight", "is_compound": False},
    {"name": "Скручивания на кабеле", "muscle_group": "abs", "equipment": "cable", "is_compound": False},
    {"name": "Ножницы", "muscle_group": "abs", "equipment": "bodyweight", "is_compound": False},
    {"name": "Дворники", "muscle_group": "abs", "equipment": "bodyweight", "is_compound": False},
    {"name": "V-образные скручивания", "muscle_group": "abs", "equipment": "bodyweight", "is_compound": False},
    {"name": "Мертвый жук", "muscle_group": "abs", "equipment": "bodyweight", "is_compound": False},
    {"name": "Прогулка фермера", "muscle_group": "forearms", "equipment": "dumbbell", "is_compound": True},
    {"name": "Прогулка фермера (с гирями)", "muscle_group": "forearms", "equipment": "kettlebell", "is_compound": True},
    {"name": "Сгибания запястий", "muscle_group": "forearms", "equipment": "barbell", "is_compound": False},
    {"name": "Обратные сгибания запястий", "muscle_group": "forearms", "equipment": "barbell", "is_compound": False},
    {"name": "Щипковый хват с блином", "muscle_group": "forearms", "equipment": "bodyweight", "is_compound": False},
    {"name": "Тяга с полотенцем", "muscle_group": "forearms", "equipment": "cable", "is_compound": True},
    {"name": "Ролик для запястий", "muscle_group": "forearms", "equipment": "bodyweight", "is_compound": False},
    {"name": "Тяга с толстым грифом", "muscle_group": "forearms", "equipment": "machine", "is_compound": True},
    {"name": "Сгибания шеи", "muscle_group": "forearms", "equipment": "bodyweight", "is_compound": False},
    {"name": "Берпи", "muscle_group": "full_body", "equipment": "bodyweight", "is_compound": True},
    {"name": "Трастеры", "muscle_group": "full_body", "equipment": "barbell", "is_compound": True},
    {"name": "Турецкий подъем", "muscle_group": "full_body", "equipment": "kettlebell", "is_compound": True},
    {"name": "Взятие на грудь и жим", "muscle_group": "full_body", "equipment": "barbell", "is_compound": True},
    {"name": "Взятие на грудь и толчок", "muscle_group": "full_body", "equipment": "barbell", "is_compound": True},
    {"name": "Рывок", "muscle_group": "full_body", "equipment": "barbell", "is_compound": True},
    {"name": "Рывок гантели", "muscle_group": "full_body", "equipment": "dumbbell", "is_compound": True},
    {"name": "Медвежья походка", "muscle_group": "full_body", "equipment": "bodyweight", "is_compound": True},
    {"name": "Толкание саней", "muscle_group": "full_body", "equipment": "sled", "is_compound": True},
    {"name": "Тяга саней", "muscle_group": "full_body", "equipment": "sled", "is_compound": True},
    {"name": "Перенос сэндбэга", "muscle_group": "full_body", "equipment": "sandbag", "is_compound": True},
    {"name": "Сэндбэг через плечо", "muscle_group": "full_body", "equipment": "sandbag", "is_compound": True},
    {"name": "Броски медбола", "muscle_group": "full_body", "equipment": "medicine_ball", "is_compound": False},
    {"name": "Передача медбола от груди", "muscle_group": "full_body", "equipment": "medicine_ball", "is_compound": False},
    {"name": "Боевые канаты", "muscle_group": "shoulders", "equipment": "resistance_band", "is_compound": True},
    {"name": "Дровосек на кабеле", "muscle_group": "abs", "equipment": "cable", "is_compound": True},
    {"name": "Антиротация на кабеле", "muscle_group": "abs", "equipment": "cable", "is_compound": False},
    {"name": "Приседания 'Гоблет' с гирей", "muscle_group": "quadriceps", "equipment": "kettlebell", "is_compound": True},
    {"name": "Взятие гири на грудь", "muscle_group": "full_body", "equipment": "kettlebell", "is_compound": True},
    {"name": "Жим гири", "muscle_group": "shoulders", "equipment": "kettlebell", "is_compound": True},
    {"name": "Гало гирей", "muscle_group": "shoulders", "equipment": "kettlebell", "is_compound": False},
    {"name": "Лэндмайн-жим", "muscle_group": "shoulders", "equipment": "barbell", "is_compound": True},
    {"name": "Ротационные отжимания 'Лэндмайн'", "muscle_group": "abs", "equipment": "barbell", "is_compound": False},
    {"name": "Ротационные подъемы 'Лэндмайн'", "muscle_group": "abs", "equipment": "barbell", "is_compound": True},
    {"name": "Ягодичный мост в Смите", "muscle_group": "glutes", "equipment": "smith_machine", "is_compound": True},
    {"name": "Болгарские сплит-приседания с гантелями", "muscle_group": "quadriceps", "equipment": "dumbbell", "is_compound": True},
    {"name": "Выпады с ходьбой с гантелями", "muscle_group": "quadriceps", "equipment": "dumbbell", "is_compound": True},
    {"name": "Наклоны 'Доброе утро' стоя с гантелями", "muscle_group": "hamstrings", "equipment": "dumbbell", "is_compound": True},
    {"name": "Пуловер на кабеле", "muscle_group": "back", "equipment": "cable", "is_compound": True},
    {"name": "Тяга к лицу на кабеле", "muscle_group": "back", "equipment": "cable", "is_compound": False},
    {"name": "Разведения рук с резинкой", "muscle_group": "back", "equipment": "resistance_band", "is_compound": False},
    {"name": "Тяга к лицу с резинкой", "muscle_group": "shoulders", "equipment": "resistance_band", "is_compound": False},
    {"name": "Протяжка с резинкой", "muscle_group": "hamstrings", "equipment": "resistance_band", "is_compound": True},
    {"name": "Тяга с резинкой", "muscle_group": "back", "equipment": "resistance_band", "is_compound": True},
    {"name": "Жим на грудь с резинкой", "muscle_group": "chest", "equipment": "resistance_band", "is_compound": True},
    {"name": "Прогулка над головой", "muscle_group": "shoulders", "equipment": "dumbbell", "is_compound": True},
    {"name": "Прогулка с чемоданом", "muscle_group": "abs", "equipment": "dumbbell", "is_compound": True},
    {"name": "Прогулка фермера одной рукой", "muscle_group": "forearms", "equipment": "dumbbell", "is_compound": True},
    {"name": "Перенос Зерхера", "muscle_group": "full_body", "equipment": "barbell", "is_compound": True},
    {"name": "Тяга с плинтов", "muscle_group": "back", "equipment": "barbell", "is_compound": True},
]

if __name__ == "__main__":
    print(f"Total exercises: {len(EXERCISE_SEED)}")
    from collections import Counter
    groups = Counter(e["muscle_group"] for e in EXERCISE_SEED)
    for g, c in sorted(groups.items()):
        print(f"  {g}: {c}")
