"""Add premium_expires_at to users

Revision ID: aeb9de67dac1
Revises: 013_add_user_admin_flags
Create Date: 2026-10-09 07:48:23.271674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb9de67dac1'
down_revision: Union[str, None] = '013_add_user_admin_flags'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('premium_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'premium_expires_at')
    # ### end Alembic commands ###